name: Paper1
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.2.0=py38h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py38h06a4308_0
  - attrs=23.1.0=py38h06a4308_0
  - babel=2.11.0=py38h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py38h06a4308_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.7=py38ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py38h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - cartopy=0.21.1=py38h1176785_0
  - certifi=2024.2.2=py38h06a4308_0
  - cffi=1.16.0=py38h5eee18b_0
  - cftime=1.6.2=py38h7deecbd_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cmocean=4.0.3=pyhd8ed1ab_0
  - colorama=0.4.6=py38h06a4308_0
  - colorlog=5.0.1=py38h06a4308_1
  - colorspacious=1.1.2=py38hb070fc8_0
  - comm=0.2.1=py38h06a4308_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - easydev=0.12.0=pyh6c4a22f_0
  - exceptiongroup=1.2.0=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.51.0=py38h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - geographiclib=2.0=py38h06a4308_0
  - geopy=2.4.1=pyhd8ed1ab_1
  - geos=3.8.0=he6710b0_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gsw=3.6.17=py38h7f0c24c_1
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.12.1=h2b7332f_3
  - icu=73.1=h6a678d5_0
  - idna=3.7=py38h06a4308_0
  - importlib-metadata=7.0.1=py38h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.1.1=py38h06a4308_1
  - ipykernel=6.28.0=py38h06a4308_0
  - ipython=8.12.2=py38h06a4308_0
  - ipywidgets=8.1.2=py38h06a4308_0
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.1.3=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py38h06a4308_0
  - jsonschema-specifications=2023.7.1=py38h06a4308_0
  - jupyter=1.0.0=py38h06a4308_9
  - jupyter-lsp=2.2.0=py38h06a4308_0
  - jupyter_client=8.6.0=py38h06a4308_0
  - jupyter_console=6.6.3=py38h06a4308_0
  - jupyter_core=5.5.0=py38h06a4308_0
  - jupyter_events=0.8.0=py38h06a4308_0
  - jupyter_server=2.10.0=py38h06a4308_0
  - jupyter_server_terminals=0.4.4=py38h06a4308_1
  - jupyterlab=4.0.11=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py38h06a4308_0
  - jupyterlab_widgets=3.0.10=py38h06a4308_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.5.0=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=hc881cc4_6
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=hc881cc4_6
  - libiconv=1.16=h7f8727e_2
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm14=14.0.6=hdb19cb5_3
  - libnetcdf=4.8.1=h14805e7_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hfdd30dd_2
  - libzip=1.8.0=h6ac8c49_1
  - llvmlite=0.36.0=py38h612dafd_4
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py38h5eee18b_0
  - matplotlib=3.7.2=py38h06a4308_0
  - matplotlib-base=3.7.2=py38h1128e8f_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mistune=2.0.4=py38h06a4308_0
  - multitaper=1.2.0=pyhd8ed1ab_0
  - mysql=5.7.24=h721c034_2
  - nbclient=0.8.0=py38h06a4308_0
  - nbconvert=7.10.0=py38h06a4308_0
  - nbformat=5.9.2=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py38h06a4308_0
  - netcdf4=1.6.2=py38h89d13dc_0
  - notebook=7.0.8=py38h06a4308_0
  - notebook-shim=0.2.3=py38h06a4308_0
  - numba=0.53.1=py38ha9443f7_0
  - numexpr=2.8.4=py38hd2a5715_1
  - numpy=1.24.3=py38hf838250_0
  - numpy-base=1.24.3=py38h1e6e340_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - overrides=7.4.0=py38h06a4308_0
  - packaging=23.2=py38h06a4308_0
  - pandas=2.0.3=py38h1128e8f_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=hebb0a14_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.3.0=py38h5eee18b_0
  - pip=23.3.1=py38h06a4308_0
  - pkgutil-resolve-name=1.3.10=py38h06a4308_1
  - platformdirs=3.10.0=py38h06a4308_0
  - ply=3.11=py38_0
  - pooch=1.7.0=py38h06a4308_0
  - proj=8.2.1=ha227179_0
  - prometheus_client=0.14.1=py38h06a4308_0
  - prompt-toolkit=3.0.43=py38h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38h06a4308_1
  - pyparsing=3.0.9=py38h06a4308_0
  - pyproj=3.4.1=py38hb83c990_0
  - pyqt=5.15.10=py38h6a678d5_0
  - pyqt5-sip=12.13.0=py38h5eee18b_0
  - pyshp=2.3.1=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py38h06a4308_0
  - python-json-logger=2.0.7=py38h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytz=2024.1=py38h06a4308_0
  - pyyaml=6.0.1=py38h5eee18b_0
  - pyzmq=25.1.2=py38h6a678d5_0
  - qt-main=5.15.2=h53bd1ea_10
  - qtconsole=5.5.1=py38h06a4308_0
  - qtpy=2.4.1=py38h06a4308_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py38h06a4308_0
  - requests=2.31.0=py38h06a4308_1
  - rfc3339-validator=0.1.4=py38h06a4308_0
  - rfc3986-validator=0.1.1=py38h06a4308_0
  - rpds-py=0.10.6=py38hb02cf49_0
  - scipy=1.10.1=py38h32ae08f_1
  - seaborn=0.12.2=py38h06a4308_0
  - send2trash=1.8.2=py38h06a4308_0
  - setuptools=68.2.2=py38h06a4308_0
  - shapely=2.0.1=py38h0fbb895_0
  - sip=6.7.12=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py38h06a4308_0
  - soupsieve=2.5=py38h06a4308_0
  - spectrum=0.8.1=py38h01eb140_2
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2020.3=hfd86e86_0
  - terminado=0.17.1=py38h06a4308_0
  - tinycss2=1.2.1=py38h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py38h06a4308_0
  - tornado=6.3.3=py38h5eee18b_0
  - traitlets=5.7.1=py38h06a4308_0
  - typing-extensions=4.9.0=py38h06a4308_1
  - typing_extensions=4.9.0=py38h06a4308_1
  - unicodedata2=15.1.0=py38h5eee18b_0
  - urllib3=2.1.0=py38h06a4308_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=0.58.0=py38h06a4308_4
  - wheel=0.41.2=py38h06a4308_0
  - widgetsnbextension=4.0.10=py38h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=py38h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
prefix: /home/ole/anaconda3/envs/Paper1
